# Day 9 – Train-Test Split & Linear Regression

## Objectives

- Separate Features & Target
- Split the data into training and testing sets
- Train a Linear Regression model
- Make predictions
- Compare actual and predicted values
- Understand how the model learns

In [8]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

pd.set_option("display.max_columns", None)

In [9]:
df = pd.read_csv("C:\\Users\\pushp\\OneDrive\\Desktop\\AI &ML project\\student-score-prediction-1\\data\\StudentPerformanceFactors.csv")

df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Study_Efficiency,Academic_Consistency,Healthy_Lifestyle_Index,Exam_Score
0,0.504942,0.348375,-0.254249,-1.380517,-1.214685,-0.019796,-0.143800,-0.393061,0.285825,-1.213934,-0.284883,0.742375,0.661006,1.070550,0.031411,-0.342867,0.103120,0.717316,0.855746,0.627550,-0.148226,0.001856,67
1,-0.162822,-1.383736,-0.254249,0.913804,-1.214685,0.661399,-1.116110,-0.393061,0.285825,0.411451,1.062448,0.742375,0.661006,-1.575587,1.001199,-0.342867,-1.248688,-0.742280,-1.168570,-0.713283,-1.433691,1.116901,61
2,0.671882,1.560853,0.901062,0.913804,0.823259,-0.019796,1.106313,0.884966,0.285825,0.411451,1.062448,0.742375,0.661006,-0.252518,1.001199,-0.342867,1.454927,0.717316,0.855746,1.414073,1.458605,0.559379,74
3,1.506587,0.781403,-0.254249,0.913804,0.823259,0.661399,1.592469,0.884966,0.285825,-0.401242,1.062448,0.742375,0.661006,-1.575587,1.001199,-0.342867,0.103120,-0.742280,0.855746,1.842914,1.715698,1.116901,71
4,-0.162822,1.041220,0.901062,0.913804,0.823259,-0.700990,-0.699406,0.884966,0.285825,1.224144,1.062448,-1.450726,0.661006,-0.252518,1.001199,-0.342867,-1.248688,0.717316,-1.168570,0.282978,-0.469593,0.001856,70

In [10]:
print("Shape :", df.shape)

display(df.head())

df.info()

Shape : (6607, 23)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Study_Efficiency,Academic_Consistency,Healthy_Lifestyle_Index,Exam_Score
0,0.504942,0.348375,-0.254249,-1.380517,-1.214685,-0.019796,-0.143800,-0.393061,0.285825,-1.213934,-0.284883,0.742375,0.661006,1.070550,0.031411,-0.342867,0.103120,0.717316,0.855746,0.627550,-0.148226,0.001856,67
1,-0.162822,-1.383736,-0.254249,0.913804,-1.214685,0.661399,-1.116110,-0.393061,0.285825,0.411451,1.062448,0.742375,0.661006,-1.575587,1.001199,-0.342867,-1.248688,-0.742280,-1.168570,-0.713283,-1.433691,1.116901,61
2,0.671882,1.560853,0.901062,0.913804,0.823259,-0.019796,1.106313,0.884966,0.285825,0.411451,1.062448,0.742375,0.661006,-0.252518,1.001199,-0.342867,1.454927,0.717316,0.855746,1.414073,1.458605,0.559379,74
3,1.506587,0.781403,-0.254249,0.913804,0.823259,0.661399,1.592469,0.884966,0.285825,-0.401242,1.062448,0.742375,0.661006,-1.575587,1.001199,-0.342867,0.103120,-0.742280,0.855746,1.842914,1.715698,1.116901,71
4,-0.162822,1.041220,0.901062,0.913804,0.823259,-0.700990,-0.699406,0.884966,0.285825,1.224144,1.062448,-1.450726,0.661006,-0.252518,1.001199,-0.342867,-1.248688,0.717316,-1.168570,0.282978,-0.469593,0.001856,70

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   float64
 1   Attendance                  6607 non-null   float64
 2   Parental_Involvement        6607 non-null   float64
 3   Access_to_Resources         6607 non-null   float64
 4   Extracurricular_Activities  6607 non-null   float64
 5   Sleep_Hours                 6607 non-null   float64
 6   Previous_Scores             6607 non-null   float64
 7   Motivation_Level            6607 non-null   float64
 8   Internet_Access             6607 non-null   float64
 9   Tutoring_Sessions           6607 non-null   float64
 10  Family_Income               6607 non-null   float64
 11  Teacher_Quality             6607 non-null   float64
 12  School_Type                 6607 non-null   float64
 13  Peer_Influence              6607 non-null   float64
 14  Physical_Activity           6607 non-null   float64
 15  Learning_Disabilities       6607 non-null   float64
 16  Parental_Education_Level    6607 non-null   float64
 17  Distance_from_Home          6607 non-null   float64
 18  Gender                      6607 non-null   float64
 19  Study_Efficiency            6607 non-null   float64
 20  Academic_Consistency        6607 non-null   float64
 21  Healthy_Lifestyle_Index     6607 non-null   float64
 22  Exam_Score                  6607 non-null   int64
dtypes: float64(22), int64(1)
memory usage: 1.2 MB

In [11]:
#separating Features & target
target = "Exam_Score"

X = df.drop(columns =[target])

Y = df[target]

In [12]:
print("Features :", X.shape)
print("Target :", Y.shape)

Features : (6607, 22)
Target : (6607,)

In [13]:
#Train Test Split
X_train , X_test, Y_train ,Y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42
)

In [14]:
print("Training Data :",X_train.shape)
print("Testing Data :", X_test.shape)

Training Data : (5285, 22)
Testing Data : (1322, 22)

In [15]:
#creating model
model = LinearRegression()

In [16]:
model.fit(X_train,Y_train)

LinearRegression()

In [17]:
#make predictions
Y_pred = model.predict(X_test)

In [18]:
#compare predictions
comparison = pd.DataFrame({
    "Actual Score " : Y_test.values,
    "Predicted Score " : Y_pred
})

comparison.head(10)

   Actual Score   Predicted Score
0             65              65.0
1             65              65.0
2             71              71.0
3             64              64.0
4             66              66.0
5             66              66.0
6             72              72.0
7             66              66.0
8             70              70.0
9             70              70.0

In [20]:
#Display model coefficient
coefficients = pd.DataFrame({
    "Features ": X.columns,
    "Coefficient": model.coef_
})

coefficients.sort_values(
    by="Coefficient",
    ascending=False
)

                     Features    Coefficient
20        Academic_Consistency  1.555858e+01
21     Healthy_Lifestyle_Index  4.815750e-15
7             Motivation_Level  3.261888e-15
0                Hours_Studied  2.715875e-15
1                   Attendance  2.338106e-15
17          Distance_from_Home  1.563936e-15
9            Tutoring_Sessions  1.228052e-15
16    Parental_Education_Level  8.716040e-16
13              Peer_Influence  1.555843e-16
15       Learning_Disabilities -1.397098e-16
18                      Gender -1.623930e-16
4   Extracurricular_Activities -4.092036e-16
3          Access_to_Resources -5.219464e-16
5                  Sleep_Hours -8.783208e-16
11             Teacher_Quality -9.029412e-16
12                 School_Type -9.748373e-16
14           Physical_Activity -1.297162e-15
8              Internet_Access -1.438049e-15
10               Family_Income -1.565016e-15
19            Study_Efficiency -6.841332e-15
2         Parental_Involvement -7.151835e-15
6              Previous_Scores -1.439869e+01

In [21]:
#intercept
print("Intercept :",model.intercept_)

Intercept : 67.23565914938702

In [22]:
#saving prediction results
comparison.to_csv(
    "C:\\Users\\pushp\\OneDrive\\Desktop\\AI &ML project\\student-score-prediction-1\\data\\StudentPerformanceFactors.csv",
    index=False
)

print("Prediction results saved")

Prediction results saved