# Day 11 – Building Student Score Prediction App

## Objectives

- Train the model
- Take user input
- Predict the exam score
- Display the prediction
- Save the trained model

In [4]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

import joblib

In [5]:
df = pd.read_csv("C:\\Users\\pushp\\OneDrive\\Desktop\\AI &ML project\\student-score-prediction-1\\data\\student_performance_processed.csv")

df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Study_Efficiency,Academic_Consistency,Healthy_Lifestyle_Index,Exam_Score
0,0.504942,0.348375,-0.254249,-1.380517,-1.214685,-0.019796,-0.143800,-0.393061,0.285825,-1.213934,...,1.070550,0.031411,-0.342867,0.103120,0.717316,0.855746,0.627550,-0.148226,0.001856,67
1,-0.162822,-1.383736,-0.254249,0.913804,-1.214685,0.661399,-1.116110,-0.393061,0.285825,0.411451,...,-1.575587,1.001199,-0.342867,-1.248688,-0.742280,-1.168570,-0.713283,-1.433691,1.116901,61
2,0.671882,1.560853,0.901062,0.913804,0.823259,-0.019796,1.106313,0.884966,0.285825,0.411451,...,-0.252518,1.001199,-0.342867,1.454927,0.717316,0.855746,1.414073,1.458605,0.559379,74
3,1.506587,0.781403,-0.254249,0.913804,0.823259,0.661399,1.592469,0.884966,0.285825,-0.401242,...,-1.575587,1.001199,-0.342867,0.103120,-0.742280,0.855746,1.842914,1.715698,1.116901,71
4,-0.162822,1.041220,0.901062,0.913804,0.823259,-0.700990,-0.699406,0.884966,0.285825,1.224144,...,-0.252518,1.001199,-0.342867,-1.248688,0.717316,-1.168570,0.282978,-0.469593,0.001856,70

In [6]:
target = "Exam_Score"

X = df.drop(columns=[target])

Y = df[target]

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42
)

In [8]:
model = LinearRegression()
model.fit(X_train,Y_train)
print("Model trained successfully!")

Model trained successfully!

In [9]:
joblib.dump(model,"C:\\Users\\pushp\\OneDrive\\Desktop\\AI &ML project\\student-score-prediction-1\\models\\student_score_model.pkl")

print("Model saved successfully!")

Model saved successfully!

In [10]:
loaded_model = joblib.load("C:\\Users\\pushp\\OneDrive\\Desktop\\AI &ML project\\student-score-prediction-1\\models\\student_score_model.pkl")

In [11]:
sample_student = X_train.iloc[[0]]

sample_student

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Study_Efficiency,Academic_Consistency,Healthy_Lifestyle_Index
5810,1.172705,-0.084652,-0.254249,-1.380517,0.823259,0.661399,-0.838307,-1.671088,0.285825,0.411451,...,0.661006,-1.575587,1.970988,-0.342867,-1.248688,-0.74228,-1.16857,1.003957,-0.662412,1.674423

In [12]:
prediction = loaded_model.predict(sample_student)
print("predicted exam score : ",round(prediction[0],2))

predicted exam score :  69.0

In [13]:
actual_score = Y_test.iloc[0]

print("Actual Score : ", actual_score)
print("Predicted Score :", round(prediction[0],2))

Actual Score :  65
Predicted Score : 69.0

In [14]:
predictions = loaded_model.predict(X_test.head(5))

results = pd.DataFrame({
    "Actual Score": Y_test.head(5).values,
    "Predicted Score": np.round(predictions, 2)
})

results

   Actual Score  Predicted Score
0            65             65.0
1            65             65.0
2            71             71.0
3            64             64.0
4            66             66.0

In [15]:
results.to_csv("C:\\Users\\pushp\\OneDrive\\Desktop\\AI &ML project\\student-score-prediction-1\\data\\final_predictions.csv", index=False)

print("Predictions saved successfully!")

Predictions saved successfully!